import type { Lesson } from '@/types';

export const lesson: Lesson = {
  id: 'fluxo-if-elif-else', trackId: 'fluxo',
  title: 'if, elif e else',
  description: 'Estruturas condicionais para tomada de decisão.',
  difficulty: 2, xp: 15, estimatedMinutes: 8,
  prerequisites: ['fluxo-comparacoes'],
  steps: [
    { id: 's1', type: 'explanation',
      content: 'O `if` executa um bloco de código apenas se uma condição for verdadeira. `elif` (else if) testa outra condição. `else` executa se nenhuma condição anterior for verdadeira.',
      codeExample: "pib_crescimento = 0.02\nif pib_crescimento > 0.03:\n    print('Economia em expansão')\nelif pib_crescimento > 0:\n    print('Crescimento lento')\nelse:\n    print('Recessão')" },
    { id: 's2', type: 'explanation',
      content: 'A **indentação** define o bloco de código. Python usa 4 espaços por convenção. Todo código no mesmo bloco deve ter a mesma indentação.',
      codeExample: 'if preco > 100:\n    print("Caro")\n    print("Considere alternativas")\nprint("Fim")  # sempre executa' },
    { id: 's3', type: 'predict-output',
      prompt: 'O que o código imprime?', code: "x = 15\nif x > 10:\n    print('A')\nelif x > 5:\n    print('B')\nelse:\n    print('C')",
      expectedOutput: 'A', hint: 'A primeira condição verdadeira é executada.' },
    { id: 's4', type: 'order-lines',
      prompt: 'Reordene as linhas para criar uma estrutura if/elif/else válida.',
      lines: ["if salario > 5000:", "    print('Alta renda')", "elif salario > 2000:", "    print('Renda média')", "else:", "    print('Baixa renda')"],
      hint: 'if primeiro, depois elif, depois else.' },
    { id: 's5', type: 'fix-bug',
      prompt: 'Corrija o erro de indentação no código abaixo.',
      buggyCode: "taxa = 0.08\nif taxa > 0.06:\nprint('Inflação alta')\nelse:\nprint('Inflação controlada')",
      tests: [],
      hint: 'O código dentro do if e do else precisa estar indentado.' },
    { id: 's6', type: 'code',
      prompt: 'Escreva uma estrutura if/elif/else que classifica: juros < 5% = barato, 5-10% = normal, > 10% = caro.',
      starterCode: "juros = 0.07\nif \n    \nelif \n    \nelse:\n    ",
      tests: [],
      hint: 'Use juros < 0.05, juros <= 0.10, else.' },
  ],
};
