import type { Track } from '@/types';

export const tracks: Track[] = [
  {
    id: 'fundamentos',
    title: 'Fundamentos de Python',
    description: 'Expressões, variáveis, tipos, strings, booleanos, entrada/saída e conversão de tipos.',
    icon: 'Code2',
    color: '#0F4C5C',
    order: 1,
    lessons: [
      'fund-expressoes',
      'fund-variaveis',
      'fund-tipos-numericos',
      'fund-strings',
      'fund-booleanos',
      'fund-entrada-saida',
      'fund-conversao-tipos',
    ],
  },
  {
    id: 'fluxo',
    title: 'Controle de Fluxo',
    description: 'Comparações, if/elif/else, operadores lógicos, laços for/while, break/continue, comprehensions.',
    icon: 'GitBranch',
    color: '#2C7A7B',
    order: 2,
    lessons: [
      'fluxo-comparacoes',
      'fluxo-if-elif-else',
      'fluxo-operadores-logicos',
      'fluxo-for',
      'fluxo-while',
      'fluxo-break-continue-range',
      'fluxo-comprehensions',
    ],
  },
  {
    id: 'estruturas-dados',
    title: 'Estruturas de Dados',
    description: 'Listas, tuplas, dicionários, conjuntos, indexação, fatiamento, mutabilidade, iteração.',
    icon: 'Database',
    color: '#358F80',
    order: 3,
    lessons: [
      'dados-listas',
      'dados-tuplas',
      'dados-dicionarios',
      'dados-conjuntos',
      'dados-indexacao-fatiamento',
      'dados-mutabilidade',
      'dados-iteracao-desempacotamento',
    ],
  },
  {
    id: 'funcoes',
    title: 'Funções em Profundidade',
    description: 'Definição, parâmetros, valores padrão, *args, **kwargs, escopo, closures, decoradores, recursão.',
    icon: 'FunctionSquare',
    color: '#3FA796',
    order: 4,
    lessons: [
      'func-definicao-chamada',
      'func-parametros-argumentos',
      'func-valores-padrao',
      'func-argumentos-nomeados',
      'func-args-kwargs',
      'func-escopo-closures',
      'func-funcoes-como-objetos',
      'func-funcoes-ordem-superior',
      'func-decoradores',
      'func-recursao',
      'func-puras-efeitos-colaterais',
      'func-composicao',
    ],
  },
  {
    id: 'classes',
    title: 'Classes e Objetos',
    description: 'Classes, instâncias, atributos, métodos, encapsulamento, herança, composição, dataclasses.',
    icon: 'Boxes',
    color: '#5B9A8B',
    order: 5,
    lessons: [
      'cls-objetos-identidade',
      'cls-classes-instancias',
      'cls-atributos',
      'cls-metodos',
      'cls-encapsulamento',
      'cls-propriedades',
      'cls-metodos-especiais',
      'cls-heranca',
      'cls-composicao',
      'cls-protocolos-polimorfismo',
      'cls-dataclasses',
      'cls-principios-projeto',
    ],
  },
  {
    id: 'intermediario',
    title: 'Python Intermediário e Avançado',
    description: 'Iteradores, geradores, context managers, exceções, módulos, type hints, testes, concorrência.',
    icon: 'Rocket',
    color: '#6BB36E',
    order: 6,
    lessons: [
      'int-iteradores-geradores',
      'int-context-managers',
      'int-excecoes',
      'int-modulos-pacotes',
      'int-type-hints',
      'int-testes',
      'int-arquivos-serializacao',
      'int-funcional',
      'int-concorrencia-async',
      'int-performance-memoria',
      'int-organizacao-projetos',
    ],
  },
  {
    id: 'economia',
    title: 'Computação para Economia',
    description: 'NumPy, pandas, visualização, séries econômicas, indicadores, econometria, otimização, ML.',
    icon: 'TrendingUp',
    color: '#FFB400',
    order: 7,
    lessons: [
      'eco-numpy',
      'eco-pandas',
      'eco-visualizacao',
      'eco-series-economicas',
      'eco-indicadores',
      'eco-engenharia-economica',
      'eco-econometria',
      'eco-otimizacao',
      'eco-series-temporais',
      'eco-ml-intro',
    ],
  },
];